### ISSUE TITLE
Generated DSL for Joins?

### ISSUE THREAD

**Issue by bali182** [stephenh/joist#16]
Hi Stephen,

I'm trying to find out how you modeled joins in the query (`Select`) DSL. Do you have any examples for that? I'm trying to do something very similar to your project in another language, but I can't think of a solution to model joins in a type-safe, but still readable way.

Thank you,
Balazs

**Comment by stephenh** [comment]
Hi Balazs,

There are some examples in this unit test:

https://github.com/stephenh/joist/blob/master/features/src/test/java/features/domain/queries/ChildQueryTest.java

But basically, no, I don't have a great way to model joins in Joist.

The core problem is that joins basically create new types...e.g. take columns a, b, c of table A, columns x, y, z of table B, put them together, and now that is basically a new type with fields a, b, c, x, y, z, that somehow ideally you need to model in the type system.

I think this is only possible in languages that: a) build it into the language, like C#'s LINQ, or b) the language has macros that can introduce new types at compile-time.

If you have any cool ideas/progress, feel free to link me to your project, I'd enjoy following along.

**Comment by bali182** [comment]
Cool, thank you very much! I'll look at the tests in more detail once I get home. I'll make sure to tell you if I manage to come up with anything, but so far I feel like I'm facing that exact problem you described.
