### ISSUE TITLE
Enable source-gen to write files with any encoding

### ISSUE THREAD

**Issue by attiand** [stephenh/joist#17]
I would like to be able to specify a Charset to be used for generated files.

```java
 public GDirectory(String directory, Charset charset) 
```

This will affect joist.util.Write which currently use the platform default encoding which becomes `ISO-8859-1` for me on Windows.

joist.util.Read explicitly specifies UTF-8 encoding.

**Comment by stephenh** [comment]
Ah cool; that makes sense. Could you submit a PR? If not, it seems ~easy, I can get around to it over the next few days.
